spring:
  data:
    mongodb:
      host: localhost
      port: 27017
swagger:
  app-info:
    name: springboot-bdshopping
    description: none
    version: 1.0.0
    license: Apache 2.0
    license-url: http://www.apache.org/licenses/LICENSE-2.0.html
  contact:
    name: MyungsunLee
    url: https://github.com/MyungsunLee/springboot-commerce
    email: naru10117@gmail.com